import type { Metadata } from "next";
import { Montserrat, Spectral } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const geistSans = Spectral({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "700", "200", "300", "600", "800"],
});

const geistMono = Montserrat({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["400", "700", "200", "300", "600", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen overflow-x-hidden`}>
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
